### ISSUE TITLE
Relaxed Test Case

### ISSUE THREAD

**Issue by jorgefandinno** [potassco/python-clingox#40] opened 2022-10-06 16:50 UTC
A common case for ```ASTTestCase``` is to test transformers. Such a test may look like
```python
def test_a(self):
    ....
    result = transform(parse_program(original_program))
    expected = parse_program(expected_program))
    self.assertEqual(result, expected)
```
where ```original_program``` and ```expected_program``` are strings representing the input and output to the transformer in gringo format, respectively.

A common problem that arises is that ```result``` and ```expected``` are identical but for some occurrence of ```clingo.Function``` in one being a corresponding ```ast.Function``` in the other.

As far as I understand this difference is unessential. 

It would be interesting to have a way to relax ```assertEqual``` to not fail in some cases. For instance, ```ASTTestCase``` may have a field ```normalize_functions``` that when made ```true``` let the assert passe and when made ```false``` causes it to fail.

**Comment by rkaminsk** [comment] 2022-10-06 17:25
This might hide unintended behavior. Having a normalize function might be helpful, though.

**Comment by jorgefandinno** [comment] 2022-10-06 19:06
Let us add the normalizing function. 

Do you think that it make sense to locate it in ```clingox.ast``` rather than in ```clingox.testing.ast```. It may be useful to apply before calling any transformer to reduce the number of cases one has to consider.

**Comment by rkaminsk** [comment] 2022-10-06 19:20
We can put it in clingox.ast because it is not necessarily tied to unit testing.

**Comment by rkaminsk** [comment] 2022-11-05 10:45
@jorgefandinno, should we close this one?

**Comment by jorgefandinno** [comment] 2022-11-05 13:17
Do you think that it makes sense to put an example in the documentation?
Otherwise we can close it.

**Comment by rkaminsk** [comment] 2022-11-05 13:31
Let's just close it. The examples are just meant to give an idea how the module is to be used and don't have to be exhaustive. Also, the function is rather easy to use so an example won't help much.

**Closed by rkaminsk** 2022-11-05 13:31 UTC
